// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'pt';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	todoList: {
		/**
		 * N​o​t​h​i​n​g​ ​h​e​r​e​ ​y​e​t​!​ ​W​h​a​t​'​s​ ​o​n​ ​y​o​u​r​ ​m​i​n​d​?
		 */
		empty: string;
		/**
		 * N​e​w​ ​t​o​d​o​.​.​.
		 */
		new: string;
		/**
		 * D​e​l​e​t​e​ ​c​o​m​p​l​e​t​e​d
		 */
		delete: string;
		/**
		 * U​p​d​a​t​e​d
		 */
		updated: string;
		alerts: {
			updateFailure: {
				/**
				 * U​p​d​a​t​e​ ​f​a​i​l​u​r​e
				 */
				title: string;
				/**
				 * C​o​u​l​d​n​'​t​ ​u​p​d​a​t​e​ ​t​h​e​ ​l​a​s​t​ ​t​o​d​o
				 */
				message: string;
			};
		};
	};
};

export type TranslationFunctions = {
	todoList: {
		/**
		 * Nothing here yet! What's on your mind?
		 */
		empty: () => LocalizedString;
		/**
		 * New todo...
		 */
		new: () => LocalizedString;
		/**
		 * Delete completed
		 */
		delete: () => LocalizedString;
		/**
		 * Updated
		 */
		updated: () => LocalizedString;
		alerts: {
			updateFailure: {
				/**
				 * Update failure
				 */
				title: () => LocalizedString;
				/**
				 * Couldn't update the last todo
				 */
				message: () => LocalizedString;
			};
		};
	};
};

export type Formatters = {};
